from typing import List, Optional
from pydantic import BaseModel, Field


class IngredientInfo(BaseModel):
    name: str
    explanation: str
    purpose: str


class Scores(BaseModel):
    overall: int = Field(ge=0, le=100)
    processing: int = Field(ge=0, le=100)
    ingredient: int = Field(ge=0, le=100)


class AnalysisResult(BaseModel):
    product_title: str = ""
    product_summary: str
    processing_level: str
    pros: List[str]
    cons: List[str]
    alternatives: List[str] = Field(default_factory=list)
    ingredients: List[IngredientInfo]
    scores: Scores
    disclaimer: str = (
        "This analysis is generated by AI for educational purposes only. "
        "It is not medical or scientific advice."
    )


class UploadResponse(BaseModel):
    image_url: str
    extracted_text: str
    ingredients_text: str


class AnalyzeRequest(BaseModel):
    product_name: Optional[str] = "Unknown Product"
    ingredients_text: str
    source: str = "manual"
    image_url: Optional[str] = None
    barcode: Optional[str] = None
    nutrition: Optional[dict] = None


class ScanSummary(BaseModel):
    id: int
    product_name: str
    source: str
    created_at: str
    overall_score: int


class ScanDetail(ScanSummary):
    ingredients_text: str
    image_url: Optional[str] = None
    barcode: Optional[str] = None
    analysis: AnalysisResult
